# Generated by Django 5.0.6 on 2025-11-06 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_minutes',
            field=models.IntegerField(default=15, verbose_name='提前提醒分钟数'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.CreateModel(
            name='AcWingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='AcWing OpenID')),
                ('access_token', models.CharField(blank=True, max_length=200, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(blank=True, max_length=200, verbose_name='刷新令牌')),
                ('photo_url', models.URLField(blank=True, verbose_name='头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acwing_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'AcWing用户',
                'verbose_name_plural': 'AcWing用户列表',
            },
        ),
    ]
