# Generated by Django 5.0.6 on 2025-11-07 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_acwinguser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QQUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='QQ OpenID')),
                ('access_token', models.CharField(blank=True, max_length=200, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(blank=True, max_length=200, verbose_name='刷新令牌')),
                ('photo_url', models.URLField(blank=True, verbose_name='头像URL')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='QQ昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'QQ用户',
                'verbose_name_plural': 'QQ用户列表',
            },
        ),
    ]
