# Generated by Django 5.0.6 on 2025-11-08 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_qquser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roamio_user_id', models.IntegerField(help_text='Roamio 项目中的用户ID', unique=True, verbose_name='Roamio 用户ID')),
                ('roamio_username', models.CharField(max_length=150, verbose_name='Roamio 用户名')),
                ('qq_unionid', models.CharField(blank=True, help_text='QQ 互联 UnionID，用于跨应用识别同一用户', max_length=100, null=True, unique=True, verbose_name='QQ UnionID')),
                ('sync_enabled', models.BooleanField(default=True, help_text='是否启用 Roamio 和 Ralendar 之间的数据同步', verbose_name='启用同步')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户映射',
                'verbose_name_plural': '用户映射表',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='email_reminder',
            field=models.BooleanField(default=False, help_text='是否发送邮件提醒', verbose_name='邮件提醒'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, help_text='地点的纬度坐标（-90 到 90）', null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, help_text='地点的经度坐标（-180 到 180）', null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='event',
            name='map_provider',
            field=models.CharField(choices=[('baidu', '百度地图'), ('amap', '高德地图'), ('tencent', '腾讯地图')], default='baidu', max_length=20, verbose_name='地图服务商'),
        ),
        migrations.AddField(
            model_name='event',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='标记提醒是否已发送', verbose_name='提醒已发送'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_trip_slug',
            field=models.CharField(blank=True, help_text='关联的 Roamio 旅行计划唯一标识', max_length=100, verbose_name='关联旅行计划Slug'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_app',
            field=models.CharField(choices=[('ralendar', 'Ralendar'), ('roamio', 'Roamio')], default='ralendar', max_length=50, verbose_name='来源应用'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='来源对象ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='地点名称'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'start_time'], name='event_user_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_app', 'source_id'], name='event_source_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['related_trip_slug'], name='event_trip_idx'),
        ),
        migrations.AddField(
            model_name='usermapping',
            name='ralendar_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roamio_mapping', to=settings.AUTH_USER_MODEL, verbose_name='Ralendar 用户'),
        ),
        migrations.AddIndex(
            model_name='usermapping',
            index=models.Index(fields=['roamio_user_id'], name='user_mapping_roamio_idx'),
        ),
        migrations.AddIndex(
            model_name='usermapping',
            index=models.Index(fields=['qq_unionid'], name='user_mapping_unionid_idx'),
        ),
    ]
